apiVersion: v1
kind: Namespace
metadata:
  name: roboshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roboshop-admin
  namespace: roboshop
subjects:
- kind: User
  name: parasuram
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: roboshop-admin
  apiGroup: rbac.authorization.k8s.io
