apiVersion: v1
kind: Namespace
metadata:
  name: roboshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roboshop-admin
  namespace: roboshop
subjects:
- kind: User
  name: parasuram
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: roboshop-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::259958482934:role/eksctl-new-cluster-nodegroup-ng-d-NodeInstanceRole-1XXVJTFWQ2E3C
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::259958482934:user/parasuram
      username: parasuram
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-05T07:14:00Z"
  name: aws-auth
  namespace: kube-system
  uid: af433b7d-0022-4e11-afa1-0c7149187027
